# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef0ae38b751e0a21edfddd1bb64debb331a14fd04aeb9097e50049758771d9a9ddc33b044b417ed600ab9e6dd7b84ab7b3e24f86c3737776090bb8755b4e521d

test:
  secret_key_base: 5f195f4a29ae1a757d6aac4bfe82d7e65e8d4b7ec9de6160ec59d24bfbc06d79d10727c666fac30eacf8a0f90865577a64e51fb519222e43cd377fbbc235bb18

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
